
services:
  db:
    image: postgres:16-alpine
    container_name: act6-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: actividad_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/3-reports_vw.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d act6-container"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://report_user:password123@db:5432/act6-container
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: